<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE def [
  <!ELEMENT def (service*)>
  <!ELEMENT service (pool, tache*)>
  <!ELEMENT pool EMPTY>
  <!ELEMENT tache (schedulejourfixe|scheduleduree|touslesjoura)>
  <!ELEMENT schedulejourfixe EMPTY>
  <!ELEMENT touslesjoura EMPTY>
  <!ELEMENT scheduleduree EMPTY>
  
  <!ATTLIST service class CDATA #REQUIRED>
  <!ATTLIST tache class CDATA #REQUIRED>
  <!ATTLIST schedulejourfixe jour (1|2|3|4|5|6|7) #REQUIRED>
  <!ATTLIST schedulejourfixe heure (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23) #REQUIRED> 
  <!ATTLIST touslesjoura heure (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23) #REQUIRED> 
  <!ATTLIST schedulejourfixe minute (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59) #REQUIRED> 
  <!ATTLIST touslesjoura minute (0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59) #REQUIRED> 
  <!ATTLIST scheduleduree nbSeconde CDATA #REQUIRED>
  <!ATTLIST pool methodeInstanciation CDATA #REQUIRED>
  <!ATTLIST pool nbThread CDATA #REQUIRED>
]>

<def>
    <service class="rssagregator.services.ServiceServer">
        <pool methodeInstanciation="newScheduledThreadPool" nbThread="2" ></pool>
        <tache class="rssagregator.services.TacheStillAlive">
            <scheduleduree nbSeconde="300"></scheduleduree>
        </tache>
    </service>
    
    <service class="rssagregator.services.ServiceCollecteur">
        <pool methodeInstanciation="newScheduledThreadPool" nbThread="30" ></pool>
        <tache class="rssagregator.services.TacheVerifComportementFluxGeneral">
            <scheduleduree nbSeconde="5000"></scheduleduree>
        </tache>
        <tache class="rssagregator.services.TacheCalculQualiteFlux">
            <schedulejourfixe jour="2" heure="2" minute="1"></schedulejourfixe>
        </tache>
    </service>
    
    <service class="rssagregator.services.ServiceMailNotifier">
        <pool methodeInstanciation="newScheduledThreadPool" nbThread="5" ></pool>
        <tache class="rssagregator.services.TacheVerifFluxNotificationMail">
            <touslesjoura heure="2" minute="0"></touslesjoura>
        </tache>
        <tache class="rssagregator.services.TacheAlerteMail">
            <touslesjoura heure="7" minute="0"></touslesjoura>
        </tache>
    </service>
    
    <service class="rssagregator.services.ServiceSynchro">
        <pool methodeInstanciation="newScheduledThreadPool" nbThread="1" ></pool>
        <tache class="rssagregator.services.TacheLancerConnectionJMS">
            <scheduleduree nbSeconde="30"></scheduleduree>
        </tache>
        <tache class="rssagregator.services.TacheSynchroHebdomadaire">
            <schedulejourfixe jour="7" heure="1" minute="1"></schedulejourfixe>
        </tache>
    </service>
</def>
